# OFN styleguide for rubocop-rspec
# Because there are so many, we will disable by default, and enable rules as needed.

Capybara:
  Enabled: false

RSpec:
  Enabled: false

FactoryBot:
  Enabled: false

RSpec/ExpectChange:
  Enabled: true
  EnforcedStyle: block

RSpec/MultipleExpectations:
  Max: 5 # Default 1

RSpec/MultipleMemoizedHelpers:
  Max: 10 # Default 5
